# Filebeat Configuration for OptiBid Energy Platform
# Collects logs and ships them to Logstash

filebeat.inputs:
  # Application logs
  - type: log
    enabled: true
    paths:
      - /var/log/optibid/application.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    fields:
      log_type: application
      app: optibid
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # Error logs
  - type: log
    enabled: true
    paths:
      - /var/log/optibid/error.log
    fields:
      log_type: error
      app: optibid
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # Security logs
  - type: log
    enabled: true
    paths:
      - /var/log/optibid/security.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    fields:
      log_type: security
      app: optibid
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # Access logs
  - type: log
    enabled: true
    paths:
      - /var/log/optibid/access.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    fields:
      log_type: access
      app: optibid
      environment: ${ENVIRONMENT:production}
    fields_under_root: true

  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# Output to Logstash
output.logstash:
  hosts: ["logstash:5000"]
  compression_level: 3
  bulk_max_size: 2048
  worker: 1

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]

# HTTP endpoint for health checks
http.enabled: true
http.host: 0.0.0.0
http.port: 5066
